### PR TITLE
New logo design

### PR DESCRIPTION
**Pull request by sindresorhus**
Created by Nadia Sotnikova: http://nadiasotnikova.com

---

screen shot 2018-05-10 at 14 24 56
screen shot 2018-05-10 at 14 25 10

### CODE REVIEW

**Comment by lukechilds** [comment]
Odd, the logo SVG doesn't display properly for me in the markdown view

screen shot 2018-05-10 at 2 42 41 pm

If I view the file directly on GitHub it's ok

**Comment by sindresorhus** [comment]
It will render when merged. Seems like a GitHub bug. They recently started supporting relative links to SVG images.

**Comment by sindresorhus** [comment]
Hmm. Yeah, doesn't work: https://github.com/sindresorhus/sindre-playground

**Comment by lukechilds** [comment]
GitHub is doing something weird to it:

https://raw.githubusercontent.com/sindresorhus/sindre-playground/master/Logo-Black-Text.svg?sanitize=true

Works fine via rawgit:

https://rawgit.com/sindresorhus/sindre-playground/master/Logo-Black-Text.svg

**Comment by sindresorhus** [comment]
Turns out GitHub sanitizes SVG files, which breaks it. Here's what they changed: https://github.com/sindresorhus/sindre-playground/commit/a337e26a403877ed6fbdb991fe4a0f361e637b67

**Comment by lukechilds** [comment]
They shouldn't do that, that's like linting code before showing it.

**Comment by sindresorhus** [comment]
They have to sanitize the SVG since it could contain JS.

**Comment by lukechilds** [comment]
Ahhh, that makes sense.

**Comment by sindresorhus** [comment]
I've contacted GitHub about the faulty sanitizer. Just using the PNG in the meanwhile.

**Comment by lukechilds** [comment]
Looks good!

**Pull request merged**
