### PR TITLE
Refactor the list of swaps into a separate component

### PR DESCRIPTION
**Pull request by sindresorhus**

### CODE REVIEW

**Comment by sindresorhus** [comment]
> I would really like to show the cancel button in the exchange view. Not important for this PR, but I think it's important to show it in the exchange view.

I think we need to make the Cancel button actually work before we put it in the Exchange view. Right now it's more annoying than it's useful because of marketmaker limitations...

**Comment by lukechilds** [comment]
Yeah, I think the positioning is exacerbating the issue though. It does work reliably if you click it before the trade gets matched, which is a pretty short time frame so only really possible from the exchange view.

But I agree, it's very confusing at the moment, I have some ideas on how to make it work a little better.

**Comment by sindresorhus** [comment]
But for active currencies like KMD/DOGE it gets matched almost right away, so I wouldn't be able to click `Cancel`. I honestly don't think cancel is useful until we make it also work *after* it gets matched.

**Comment by lukechilds** [comment]
I did ask James previously to allow cancelling in-progress swaps but he was strongly opposed to it.

I will ask him again.

**Comment by lukechilds** [comment]
@sindresorhus https://github.com/lukechilds/hyperdex/issues/262#issuecomment-395390245

**Pull request merged**
